#!/bin/bash
#
# galliumos-baytrail postinst
#

## Update GRUB when /etc/default/grub.d/galliumos-baytrail.cfg changes
## TODO: only when it changes

if [ -e /boot/grub/grub.cfg ] && which update-grub >/dev/null 2>&1; then
  update-grub || true
fi


## PulseAudio manipulations. This might no longer be needed?

systemctl daemon-reload
systemctl unmask galliumos-baytrail
systemctl enable galliumos-baytrail
systemctl start galliumos-baytrail
alsactl restore

exit 0
