#!/bin/bash

alsactl restore
echo "----------IMPORTANT!----------"
echo "Existing installs may have issues with the default sink in PulseAudio"
echo "To fix this, please reboot the system or restart PulseAudio."
echo "If it still doesn't work, change the default sink in pavucontrol to"
echo "byt-max98090."
exit 0
