#!/bin/bash

systemctl daemon-reload
systemctl enable galliumos-baytrail
systemctl start galliumos-baytrail

alsactl restore
echo "Audio may stop working after updating the galliumos-baytrail package"
echo "Please reboot the computer."
echo "----------IMPORTANT!----------"
echo "Existing installs may have issues with the default sink in PulseAudio"
echo "To fix this, please reboot the system or restart PulseAudio."
echo "If it still doesn't work, change the default sink in pavucontrol to"
echo "byt-max98090."
exit 0
